# This is really slow since building it seems to take forever, so
# getting it off the fast path helps.

name: Security audit
on:
  schedule:
    - cron: "37 8 * * 6"
  push:
    paths:
      - "**/Cargo.*"
  pull_request:
    branches:
      - master
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: workaround a cache bug
        run: mkdir target

      - name: cache rust build artifacts
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.OS }}-build2-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build2-

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
